import { SidebarsConfig } from '@docusaurus/plugin-content-docs';

export default {
  myAutogeneratedSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    },
  ],
};